### ISSUE TITLE
named_routes.helpers deprecation warning when testing cells in rSpec with Rails 4.2

### ISSUE THREAD

**Issue by reconstructions** [apotonick/cells#269] opened 2015-02-27 02:03 UTC
I am getting a deprecation warning in Rails 4.2, rSpec 3.2 when testing my cells. For example:

```
DEPRECATION WARNING: `named_routes.helpers` is deprecated, please use `route_defined?(route_name)` to see if a named route was defined. (called from block (2 levels) in <top (required)> at /Users/reconstructions/Desktop/Coding 2013/Rails Apps/sfrc/spec/cells/instrument_cell_spec.rb:8)
```

And the test:

```ruby
expect(cell(:instrument, @instrument).musician_type_name_sing).to have_content("Bassist")
```

I get them for every test I run on a cell.  Thanks in advance...

**Comment by apotonick** [comment] 2015-02-27 04:21
Aaand: what Cells version?

**Comment by reconstructions** [comment] 2015-02-27 04:33
3.11.3

**Comment by dgilperez** [comment] 2015-03-22 23:20
:+1:

**Comment by dgilperez** [comment] 2015-03-23 00:09
Fixed in rspec-rails like this: https://github.com/rspec/rspec-rails/issues/1187 and caused by the usage of ``named_routes.helpers`` in rspec-cells: https://github.com/apotonick/rspec-cells/search?utf8=%E2%9C%93&q=named_routes.helpers

**Comment by apotonick** [comment] 2015-05-22 23:44
Fixed in 0.3.0 (only Cells 4, though).

Are you considering upgrading Cells, or should I backport the feature?

**Closed by apotonick** 2015-05-22 23:44 UTC

**Comment by incorvia** [comment] 2015-06-02 20:57
If this is easy to backport would be nice.

**Comment by apotonick** [comment] 2015-06-02 22:28
Not a priority, though, since it's just a warning, right? @incorvia It's simple, you can try. Here's how it's done in Cells 4: https://github.com/apotonick/rspec-cells/blob/master/lib/rspec/cells/example_group.rb#L21
