### ISSUE TITLE
Asset path helpers that conflict with controller paths do not work consistently in cells vs views

### ISSUE THREAD

**Issue by andypike** [apotonick/cells#266] opened 2015-02-18 23:14 UTC
Hi everyone, 

Let me explain what I'm seeing and hopefully it will make some kind of sense. So I'm working on this project: https://github.com/andypike/ruby_videos which uses the following gems:

* rails 4.2
* cells 4.0.0.beta2
* cells-slim master

I have a `Video` model and I'm trying to add a link to a `show` action on the `VideosController` so naturally I'm trying to use `video_path(model)` from inside my cell slim file. When this renders the link the href is something like `/videos/#<Video:0x007fefc3840200>` rather than the expected `/videos/1`. 

If I use `video_path(model.to_param)` then it works fine. As a test I tried using `video_path(model)` inside a normal rails view (not a cell) and it rendered the expected href.

I guess this is due to the asset helper path `video_path` that rails exposes   (http://api.rubyonrails.org/classes/ActionView/Helpers/AssetUrlHelper.html#method-i-video_path) not following the same override rules in cells as rails views do.

This is not a massive problem because I can use the workaround mentioned above but I thought you would like to know about it. 

If you need any help then please let me know.

Thanks in advance

Andy

PS Lovin' the gem, great work :heart: :heart: :heart:

**Comment by apotonick** [comment] 2015-02-19 06:09
Hey Andy,

thanks! Rails and its helpers are a pest and the way it's implemented is "improvable" :wink: - could you give this a go? https://github.com/apotonick/cells/wiki/Troubleshooting#rendering-problems

What if you include the `AssetUrlHelper` in your cell?

**Comment by andypike** [comment] 2015-02-19 13:32
Thanks for the reply Nick. I added `include ActionView::Helpers::AssetUrlHelper` to the cell but it still renders `video_path(model)` as `/videos/#<Video:0x007fda549c8f48>`. 

I'm happy to help if there are other things you would like me to try :smile: 

Andy

**Comment by apotonick** [comment] 2015-02-24 18:17
Hm, this might actually be a good occasion to fix this in Rails itself.

I am meeting @rafaelfranca and @carlosantoniodasilva in a few days and maybe we can go through it with some cervecas and discuss how to deal with this annoying design flaw in the future?

**Comment by andypike** [comment] 2015-02-26 20:49
Thanks Nick, if there is anything I can help with then just let me know :heart:

**Comment by carlosantoniodasilva** [comment] 2015-03-03 13:45
@apotonick :+1: please feel free to bring this discussion :)

**Comment by apotonick** [comment] 2015-06-05 10:37
Hey @andypike, sorry for the late reply.

I was able to reproduce this bug, but at the same time couldn't find where the actual `model.to_params` in the sprockets helper happens. If you find it out, I'll fix it.

Went through your repository - looks great! First I thought you were already using Trailblazer due to the `app/concepts` directory, but .. not _yet_!

A lot of things have happened in Cells 4 - can you upgrade to the release candidate and see if your tests still pass? Thanks! :heart:

**Comment by andypike** [comment] 2015-06-05 12:07
Thanks @apotonick, I'll upgrade to the RC and see what happens.

I started using Trailblazer but there were a few things I wanted to do differently but loved the idea of concepts and cells so kept those bits. Maybe I should do a blog post with more details if you would find that interesting?

Thanks again :sparkling_heart:

**Comment by apotonick** [comment] 2015-06-05 12:08
Ehm... did anyone say "blog post"??????? :tada: :beers: :laughing:

**Comment by andypike** [comment] 2015-06-05 21:21
Updated to RC and everything worked as before :) I'll try to free up some time to investigate this issue and will let you know if I get anywhere.

**Comment by apotonick** [comment] 2016-05-03 03:38
This should be fixed in 4.1.0 in combination with https://github.com/trailblazer/cells-rails.

**Closed** 2016-05-03 03:39 UTC
